const ErrorCodes = {
    INVALID_TYPES_ERROR: 1, 
    MISSING_REQUIRED_FIELDS: 2, 
    INVALID_FORMAT: 3, 
    EXISTING_DATA: 4,
    INVALID_CREDENTIALS: 5,
    UNAUTHORIZED_ACCESS: 6,
    NOT_FOUND: 7,
    OUT_OF_STOCK: 8, 
    PAYMENT_FAILED: 9
}

export default ErrorCodes